"""Public API for the configuration module."""

from .loader import (
    generate_run_id,
    get_git_commit,
    load_config,
    parse_cli_overrides,
    save_resolved_config,
)
from .schema import (
    REGISTERED_MODELS,
    BacktestConfig,
    BlockBootstrapConfig,
    ControlPolicyConfig,
    DataConfig,
    DatasetConfig,
    ExecutionHeadsConfig,
    ExperimentConfig,
    FeatureConfig,
    IngestionConfig,
    LabelConfig,
    LatentStateConfig,
    MarketMakingConfig,
    ModelRunConfig,
    MonthlySnapshotConfig,
    NormalisationConfig,
    OrderBookConfig,
    QueueFillConfig,
    ReturnHeadConfig,
    RobustnessConfig,
    SamplingConfig,
    SplitConfig,
    SyntheticConfig,
)

__all__ = [
    # Schema
    "ExperimentConfig",
    "DataConfig",
    "MonthlySnapshotConfig",
    "SamplingConfig",
    "LabelConfig",
    "SplitConfig",
    "FeatureConfig",
    "ModelRunConfig",
    "BacktestConfig",
    "MarketMakingConfig",
    "QueueFillConfig",
    "ControlPolicyConfig",
    "LatentStateConfig",
    "ExecutionHeadsConfig",
    "ReturnHeadConfig",
    "RobustnessConfig",
    "BlockBootstrapConfig",
    "IngestionConfig",
    "SyntheticConfig",
    "NormalisationConfig",
    "OrderBookConfig",
    "DatasetConfig",
    "REGISTERED_MODELS",
    # Loader
    "load_config",
    "save_resolved_config",
    "generate_run_id",
    "get_git_commit",
    "parse_cli_overrides",
]
